Echo error to stderr

diff --git a/.bin/bak b/.bin/bak
--- a/.bin/bak
+++ b/.bin/bak
@@ -12,6 +12,6 @@ for FILE in "$@"; do
         ;;
     esac
   else
-    echo "$FILE not found"
+    echo "$FILE not found" 1>&2
   fi
 done
