Enable to cache downloaded URL

diff --git a/.bin/download-urls b/.bin/download-urls
--- a/.bin/download-urls
+++ b/.bin/download-urls
@@ -2,12 +2,72 @@
 
 set -euo pipefail
 
+cache_file=''
+
+filename_mode_original='Original'
+filename_mode_index='Indexed'
+
+urls_not_cached=()
+
+check_cache() {
+  url=${1:-}
+
+  if [[ ! "$url" ]]; then
+    echo "Missing url for check_cache" 1>&2
+    exit 1
+  fi
+
+  if [[ ! -f "$cache_file" ]]; then
+    echo false
+  fi
+
+  while read -r line; do
+    [[ "$line" == "$url" ]] && {
+      echo true
+      return
+    }
+  done < "$cache_file"
+
+  echo false
+}
+
+for OPT in "$@"; do
+  case $OPT in
+    --cache)
+      cache_file=${2:-}
+      if [[ ! -f "$cache_file" ]]; then
+        touch "$cache_file"
+      fi
+
+      shift 2
+      ;;
+    -*)
+      echo "Unknown option: $1" 1>&2
+      exit 1
+      ;;
+  esac
+done
+
 if [[ "$#" == 0 ]]; then
   exit 0
 fi
 
-filename_mode_original='Original'
-filename_mode_index='Indexed'
+if [[ "$cache_file" ]]; then
+  for url in "$@"; do
+    is_cached=$(check_cache "$url")
+
+    if [[ "$is_cached" == false ]]; then
+      urls_not_cached+=("$url")
+    fi
+  done
+else
+  urls_not_cached+=("$@")
+fi
+
+if [[ "${#urls_not_cached[@]}" == 0 ]]; then
+  echo 'All urls cached'
+  exit 0
+fi
 
 filename_mode=$(printf "%s\n%s" \
   "$filename_mode_original" "$filename_mode_index" \
@@ -20,7 +80,7 @@ fi
 tmpdir=$(mktemp -d -p .)
 
 i=0
-for url in "$@"; do
+for url in "${urls_not_cached[@]}"; do
   if [[ "$filename_mode" == "$filename_mode_original" ]]; then
     curl -O -J "$url"
   elif [[ "$filename_mode" == "$filename_mode_index" ]]; then
@@ -29,6 +89,10 @@ for url in "$@"; do
     curl --output-dir "$indexed_dir" -O -J "$url"
   else
     exit 1
+  fi
+
+  if [[ "$cache_file" ]]; then
+    echo "$url" >> "$cache_file"
   fi
 
   i=$((i + 1))
