Echo error to stderr

diff --git a/.bin/loc b/.bin/loc
--- a/.bin/loc
+++ b/.bin/loc
@@ -68,8 +68,8 @@ for OPT in "$@"; do
       ;;
     -w | --which)
       if [[ -z "$2" ]]; then
-        echo 'Command name not provided for -w option'
-        echo 'Usage: loc -w <command_name>'
+        echo 'Command name not provided for -w option' 1>&2
+        echo 'Usage: loc -w <command_name>' 1>&2
         exit 1
       fi
 
@@ -93,14 +93,14 @@ for OPT in "$@"; do
 done
 
 if [[ "$command_name" == '' ]]; then
-  echo 'Command name not passed'
+  echo 'Command name not passed' 1>&2
   exit 1
 fi
 
 command_body=$(get_cmd_body "$command_name")
 
 if [[ "$command_body" == '' ]]; then
-  echo "Command not found: LOC_CMD_$command_name"
+  echo "Command not found: LOC_CMD_$command_name" 1>&2
   exit 1
 elif [[ $# -eq 0 ]]; then
   echo "$command_body"
diff --git a/.config/zsh/fn/fdcd b/.config/zsh/fn/fdcd
--- a/.config/zsh/fn/fdcd
+++ b/.config/zsh/fn/fdcd
@@ -2,12 +2,12 @@ fdcd() {
   local file dirname
 
   if ! hascommand fd; then
-    echo 'Command not found: fd'
+    echo 'Command not found: fd' 1>&2
     return 1
   fi
 
   if ! hascommand fzf; then
-    echo 'Command not found: fzf'
+    echo 'Command not found: fzf' 1>&2
     return 1
   fi
 
