Rewrite error messages

diff --git a/.bin/loc b/.bin/loc
--- a/.bin/loc
+++ b/.bin/loc
@@ -59,7 +59,7 @@ get_cmd_body() {
 
   cmd_name=${1:-}
   if [[ ! "$cmd_name" ]]; then
-    echo "Command name not passed for get_cmd_body" 1>&2
+    echo "Missing command name for get_cmd_body" 1>&2
     exit 1
   fi
 
@@ -90,8 +90,8 @@ for OPT in "$@"; do
       command_name_which=${2:-}
       command_name_which=${command_name_which^^}
       if [[ ! "$command_name_which" ]]; then
-        echo 'Command name not provided for -w option' 1>&2
-        echo 'Usage: loc -w <command_name>' 1>&2
+        echo 'Missing command name for -w option' 1>&2
+        echo 'USAGE: loc -w <command_name>' 1>&2
         exit 1
       fi
 
@@ -116,7 +116,7 @@ for OPT in "$@"; do
 done
 
 if [[ ! "${command_name:-}" ]]; then
-  echo 'Command name not passed' 1>&2
+  echo 'Missing command name' 1>&2
   exit 1
 fi
 
