Rewrite error messages

diff --git a/.bin/repo b/.bin/repo
--- a/.bin/repo
+++ b/.bin/repo
@@ -11,7 +11,7 @@ open() {
   repo=${1:-}
 
   if [[ ! "$repo" ]]; then
-    echo 'Repo not provided' 1>&2
+    echo 'Missing repo' 1>&2
     exit 1
   fi
 
