Refactor `fdcd`

diff --git a/.zsh/fn/fdcd b/.zsh/fn/fdcd
--- a/.zsh/fn/fdcd
+++ b/.zsh/fn/fdcd
@@ -1,6 +1,21 @@
 fdcd() {
   local file dirname
-  file=$(fd --max-results 1000 $@ | fzf --ansi) &&
-  dirname=$(dirname $file) &&
-  cd $dirname
+
+  if ! hascommand fd; then
+    echo 'Command not found: fd'
+    return 1
+  fi
+
+  if ! hascommand fzf; then
+    echo 'Command not found: fzf'
+    return 1
+  fi
+
+  file=$(fd --max-results 1000 "$@" | fzf --ansi)
+  [[ "$file" == "" ]] && return 1
+
+  dirname=$(dirname "$file")
+  [[ "$dirname" == '' ]] && return 1
+
+  cd "$dirname" || return
 }
